default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: sparschwein_development

test:
  <<: *default
  database: sparschwein_test

production:
  <<: *default
  database: sparschwein_production
